""" 389. Find the Difference (Easy)
https://leetcode.com/problems/find-the-difference/

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

* Input:
* s = "abcd"
* t = "abcde"
* Output:
* e
* Explanation:
* 'e' is the letter that was added. """

# TODO: Approach 1: Bit manipulation (XOR) - convert to unicode and use XOR to find single number   [O(max(s,t)) & O(1)]


class Solution:
    def findTheDifference(self, s: str, t: str) -> int:
        ch = 0

        for char_ in s:
            ch ^= ord(char_)

        for char_ in t:
            ch ^= ord(char_)

        return chr(ch)


if __name__ == "__main__":
    s, t = "abcd", "abcde"  # ? Output = "e"

    solution = Solution()
    result = solution.findTheDifference(s, t)

    print("Result is {}".format(result))
